# Site settings
title: Love, Burt Macklin - FBI
tagline: Site Tagline
author :
  name : Jordan Burke
  email : me@jordankburke.com
  github : PendragonDevelopment
  twitter : PendragonDev
subtitle: The personal blog of Jordan Burke, Digital Enabler.
description: > # this means to ignore newlines until "baseurl:"
  The uninspired rantings of a madman with a box.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.jordankburke.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

permalink: /:categories/:year/:month/:day/:title

exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]
highlighter: pygments